Remove an empty gossip_menu_option entry for hunter trainer.
mangosone/database pull request #109
Opened 2021-03-29 19:12 UTC by haruzept

This entry show up a blank entry for hunter trainer.

2021-03-29 19:34 UTC, haruzept commented
This entry is not required because it is duplicated.

2021-03-30 12:56 UTC, Necrovoice commented
Will take care of this once I get home.

2021-03-31 12:21 UTC, Necrovoice commented
Changing the base files is not required. If you could resubmit with only the update script.
 - Thanks

2021-04-02 18:33 UTC, billy1arm requested changes
@haruzept - Please can you remove the gossip+menu_option changes from this pr

The base files are never changed

2021-04-02 19:14 UTC, billy1arm commented
changes added via Commit: https://github.com/mangosone/database/commit/c066568b996e6df9100ebb111c1ff9db3ad7b1c1

2021-04-02 19:14 UTC, closed without merging

2021-04-08 20:18 UTC, billy1arm commented on World/Updates/Rel22/Rel22_01_028_empty_gossip_menu_option_for_hunter_trainer.sql
> +    SET @cNewDescription = 'empty gossip menu option for hunter trainer ';
@haruzept - Please ensure that this field is never longer than 30 characters, otherwise the update will not apply